// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZ-t7abKiOUSdx7QhpWFWKlq4JToB8Ps',
    appId: '1:785417525110:web:0401303feea18c58fa8c57',
    messagingSenderId: '785417525110',
    projectId: 'titliyaan-2db47',
    authDomain: 'titliyaan-2db47.firebaseapp.com',
    storageBucket: 'titliyaan-2db47.appspot.com',
    measurementId: 'G-HRTK0HN55M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUsskWVoKxyluzPHEBKVK45MM2ergaIM',
    appId: '1:785417525110:android:8806942dc1a1d1a3fa8c57',
    messagingSenderId: '785417525110',
    projectId: 'titliyaan-2db47',
    storageBucket: 'titliyaan-2db47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRtBEER3JkyzX59ux4oF4UNTeB_snxok',
    appId: '1:785417525110:ios:901a2053ce976382fa8c57',
    messagingSenderId: '785417525110',
    projectId: 'titliyaan-2db47',
    storageBucket: 'titliyaan-2db47.appspot.com',
    iosClientId:
        '785417525110-7oqfb35kecs186jerv83fp4thfa2biv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.titliyaan',
  );
}
